name: Run Nexus Testnet Node
on:
  schedule:
    - cron: "0 */6 * * *"  # otomatis jalan tiap 6 jam
  workflow_dispatch:

jobs:
  run-nexus:
    runs-on: ubuntu-latest
    steps:
      - name: Install and run Nexus node
        run: |
          sudo apt update
          sudo apt install -y curl
          curl https://cli.nexus.xyz/ | sh
          source ~/.bashrc
          ~/.nexus/bin/nexus-network start --node-id 6328801
