name: Run Nexus Testnet Node
on:
  schedule:
    - cron: "0 */6 * * *"  # jalan tiap 6 jam
  workflow_dispatch:

jobs:
  run-nexus:
    runs-on: ubuntu-latest
    steps:
      - name: Setup and run Nexus node
        run: |
          sudo apt update
          sudo apt install -y curl
          echo "y" | curl https://cli.nexus.xyz/ | sh
          export PATH=$PATH:$HOME/.nexus/bin
          echo "Starting Nexus node..."
          ~/.nexus/bin/nexus-network start --node-id 6328801 < /dev/null & sleep 60
          echo "Nexus node started successfully!"
